task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from allauth.account.decorators import secure_admin_login

admin.autodiscover()
admin.site.login = secure_admin_login(admin.site.login)

urlpatterns = [
    path('', RedirectView.as_view(pattern_name="projects:projects_list", permanent=False)),
    path('admin/', admin.site.urls),
    path('projects/', include('todo_list.urls')),

    path('accounts/', include('custom_auth.urls')),
  
]

todo_list/urls.py
from django.urls import path
from . import views

app_name ='projects'

urlpatterns = [
    path('', views.ProjectListView.as_view(), name='projects_list'),
    
    path('create/', views.ProjectCreateView.as_view(), name='projects_create'),
    path('delete/<int:pk>/', views.ProjectDeleteView.as_view(), name='projects_delete'),
    path('update/<int:pk>/', views.ProjectUpdateView.as_view(), name='projects_update'),

    path('<int:project_id>/task/create/', views.TaskCreateView.as_view(), name='task_create'),
    path('task/delete/<int:pk>/', views.TaskDeleteView.as_view(), name='task_delete'),
    path('task/update/<int:pk>/', views.TaskUpdateView.as_view(), name='task_update'),
    path('task/completed/<int:pk>/', views.TaskCompletedUpdateView.as_view(), name='task_completed'),
    path('task/priority/<int:pk>/', views.TaskPriorityUpdateView.as_view(), name='task_priority'),
]

todo_list/models.py
from datetime import datetime, timedelta

from django.db import models
from django.contrib.auth.models import User


class Project(models.Model):
    owner = models.ForeignKey(
        User,
        related_name="projects",
        on_delete=models.CASCADE,
        )
    name = models.CharField(max_length=50)

    def __str__(self):
        return f"Project: {self.name}"


class Task(models.Model):
    project = models.ForeignKey(
        Project,
        related_name="tasks",
        on_delete=models.CASCADE,
        )
    content = models.CharField(max_length=100)
    priority = models.IntegerField(default=0)
    completed  = models.BooleanField(default=False)
    deadline = models.DateField(
        default=(datetime.today() + timedelta(days=1)).date(),
        )

    def __str__(self):
        return f"Project: {self.content[:10]}..."
    
    class Meta:
        ordering = ["-priority"]

todo_list/forms.py
from django import forms

from .models import Project, Task


class PriorityTaskForm(forms.ModelForm):
    
    def __init__(self, *args, instance=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.task = instance

    def clean_priority(self, **kwargs):
        priority_db = self.task.priority
        change_val = self.cleaned_data['priority']
        if  change_val == 1 and priority_db == 10:
            raise forms.ValidationError("Priority is maximum")
        if  change_val == -1 and priority_db == 0:
            raise forms.ValidationError("Priority is minimum")
        return change_val
        

    class Meta:
        model = Task
        fields = ['priority']


class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ['content', 'deadline']
        
        widgets = {
            'content': forms.TextInput(attrs={
                'class': "form-control",
                'autocomplete': "off",
                'autofocus': 'true',
                'required': 'true',
            }),
            'deadline': forms.DateInput(attrs={
                'class': "form-control",
                'type': 'date',
            }),
        }


class ProjectForm(forms.ModelForm):
        
    class Meta:
        model = Project
        fields = ['name']

        widgets = {
            'name': forms.TextInput(attrs={
                'class': "form-control",
                'autocomplete': "off",
                'autofocus': 'true',
                'required': 'true',
                'placeholder': 'Your new project name',
            }),
        }

todo_list/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseNotAllowed
from django.db.models import F
from django.forms import ValidationError
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from .models import Project, Task
from .forms import PriorityTaskForm, TaskForm, ProjectForm


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    context_object_name = 'projects'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(owner=self.request.user)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class ProjectCreateView(LoginRequiredMixin, CreateView):
    form_class = ProjectForm
    model = Project
    success_url = reverse_lazy('projects:projects_list')
    template_name = "todo_list/partials/project_form.html"
    
    def get(self, request, *args, **kwargs):
        if request.headers.get("HX-Request") == "true":
            return super().get(request, *args, **kwargs)
        else:
            return redirect('projects:projects_list')
        
    def form_valid(self, form):
        form.instance.owner = self.request.user
        if self.request.headers.get("HX-Request") == "true":
            self.object = form.save()
            return render(self.request, 'todo_list/project.html', self.get_context_data())
        else:
            return super().form_valid(form)


class ProjectUpdateView(LoginRequiredMixin, UpdateView):
    form_class = ProjectForm
    model = Project
    success_url = reverse_lazy('projects:projects_list')
    template_name = 'todo_list/project_title.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(owner=self.request.user)
    
    def get(self, request, *args, **kwargs):
        if request.headers.get("HX-Request") == "true":
            project = Project.objects.filter(
                pk=self.kwargs['pk'],
                owner = self.request.user
                ).first()
            if project is None:
                return HttpResponseNotFound()
            context = {"project": project,
                       "form": ProjectForm(instance=project)
                       }
            return render(self.request, 'todo_list/partials/project_update.html', context)
        else:
            return redirect('projects:projects_list')
    
    def form_valid(self, form):
        if self.request.headers.get("HX-Request") == "true":
            self.object = form.save()
            return render(self.request, self.get_template_names(), self.get_context_data())
        else:
            return super().form_valid(form)


class ProjectDeleteView(LoginRequiredMixin, DeleteView):
    model = Project
    http_method_names = ['post']
    success_url = reverse_lazy('projects:projects_list')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(owner=self.request.user)
    
    def form_valid(self, form):
        super().form_valid(form)
        if self.request.headers.get("HX-Request") == "true":
            return HttpResponse(status=200)
        else:
            success_url = self.get_success_url()
            return redirect(success_url)
    

class TaskCreateView(LoginRequiredMixin, CreateView):
    fields = ['content']
    model = Task
    success_url = reverse_lazy('projects:projects_list')
    template_name = "todo_list/task_list.html"
    
    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.project = Project.objects.filter(
            pk=self.kwargs['project_id'],
            ).first()
    
    def get(self, request, *args, **kwargs):
        if (self.project is None or
             self.project.owner != self.request.user
             ):
            return HttpResponseNotFound()
        if request.headers.get("HX-Request") == "true":
            context = {
                "project": self.project,
                'form': TaskForm(),
            }
            return render(self.request, "todo_list/partials/full_task_form.html", context)
        else:
            return redirect('projects:projects_list')
    
    def form_valid(self, form):
        if self.project.owner != self.request.user:
            return HttpResponseNotFound()
        form.instance.project = self.project
        if self.request.headers.get("HX-Request") == "true":
            self.object = form.save()
            context = self.get_context_data()
            context['project'] = self.project
            return render(self.request, "todo_list/task_list.html", context)
        else:
            return super().form_valid(form)
    
    
class BaseUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    
    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(project__owner=self.request.user)
    
    
class TaskUpdateView(BaseUpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy('projects:projects_list')
    template_name = "todo_list/task_list.html"

    def get(self, request, *args, **kwargs):
        task = Task.objects.filter(
            pk=self.kwargs['pk'],
            project__owner=self.request.user
            ).first()
        if task is None:
            return HttpResponseNotFound()
        if request.headers.get("HX-Request") == "true":
            context = {
                'task': task,
                'form': TaskForm(instance=task),
            }
            return render(self.request, "todo_list/partials/task_update_form.html", context)
        else:
            return redirect('projects:projects_list')
        
    def form_valid(self, form):
        if self.request.headers.get("HX-Request") == "true":
            self.object = form.save()
            context = self.get_context_data()
            context['project'] = self.object.project
            return render(self.request, 'todo_list/partials/one_task.html', context)
        else:
            return super().form_valid(form)
    

class TaskCompletedUpdateView(BaseUpdateView):
    http_method_names = ['post']
    fields = ['completed']
    
    def form_valid(self, form):
        if self.request.headers.get("HX-Request") == "true":
            task = self.get_object()
            Task.objects.filter(id=task.id).update(completed=~F("completed"))
            return HttpResponse(status=200)
        else:
            return HttpResponseNotAllowed(permitted_methods='hx-post')
    

class TaskPriorityUpdateView(BaseUpdateView):
    http_method_names = ['post']
    form_class = PriorityTaskForm
    template_name = "todo_list/task_list.html"

    def form_valid(self, form):
        
        if self.request.headers.get("HX-Request") == "true":
            task = self.get_object()
            task.priority += form.cleaned_data['priority']
            task.save()
            return render(self.request, self.get_template_names(), self.get_context_data())
        else:
            return HttpResponseNotAllowed(permitted_methods='hx-post')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['project'] = self.get_object().project
        return context

    
class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    http_method_names = ['post']
    success_url = reverse_lazy('projects:projects_list')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(project__owner=self.request.user)
    
    def form_valid(self, form):
        super().form_valid(form)
        if self.request.headers.get("HX-Request") == "true":
            return HttpResponse(status=200)
        else:
            success_url = self.get_success_url()
            return redirect(success_url)

templates/todo_list/project.html
{% load static %}
<div id="project-{{project.id}}">
{% include 'todo_list/project_title.html' with project=project %}
{% include 'todo_list/task_list.html' with task=task %}
</div>

  

templates/todo_list/project_form.html
{% load static %}
<div class="d-flex justify-content-between p-3 my-5 mb-0 text-white bg-blue  shadow-sm" id="project-update-{{project.id}}">
  <div>
    <h1 class="h3 mb-0 text-white lh-1"><i class="bi bi-calendar2-check fs-3 me-4"></i>{{project.name}}</h1>
  </div>
  <div>
    <form class="form-display"
        hx-post="{% url 'projects:projects_delete' project.id %}" 
        hx-target="#project-{{project.id}}"
        hx-swap="delete"
        hx-confirm="Are you sure you wish to delete project: {{project.name}}?">
        {% csrf_token %}
        <button type="submit" class="btn btn-link p-0 m-0 align-baseline">
          <i class="bi bi-trash "></i>
        </button>
    </form>
    <form class="form-display"
        hx-get="{% url 'projects:projects_update' project.id %}" 
        hx-target="#project-update-{{project.id}}"
        hx-swap="outerHTML">
      {% csrf_token %}
      <button type="submit" class="btn btn-link p-0 m-0 align-baseline">
      <i class="bi bi-pencil"></i>
      </button>
    </form>
  </div>  
</div>

templates/todo_list/project_list.html
{% extends 'base.html' %}
{% load static %}

{% block projects_list %}
<div id="project_list">

{% include 'navbar.html' %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-success d-flex align-items-center" role="alert">
  <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
  <div>
    {{ message }}
  </div>
</div>
{% endfor %}
{% endif %}
<main class="container" >
  {% for project in projects %}
    {% include 'todo_list/project.html' with project=project %}
  {% endfor %}
  <div class="d-flex justify-content-center my-5" id="new-project">
    <form hx-get="{% url 'projects:projects_create' %}"
        hx-target="#new-project"
        hx-swap="beforebegin">
        {%csrf_token%}
        <button type="submit" class="btn btn-primary rounded-pill px-4  btn-lg">
          <i class="bi bi-plus-circle-dotted fs-4 "></i>
          Add TODO
      </button>
    </form>
  </div>
</main>
</div>

{%endblock%}

templates/todo_list/project_title.html
{% load static %}
<div class="d-flex justify-content-between p-3 my-5 mb-0 text-white bg-blue  shadow-sm" id="project-update-{{project.id}}">
  <div>
    <h1 class="h3 mb-0 text-white lh-1"><i class="bi bi-calendar2-check fs-3 me-4"></i>{{project.name}}</h1>
  </div>
  <div>
    <form class="form-display"
        hx-post="{% url 'projects:projects_delete' project.id %}" 
        hx-target="#project-{{project.id}}"
        hx-swap="delete"
        hx-confirm="Are you sure you wish to delete project: {{project.name}}?">
        {% csrf_token %}
        <button type="submit" class="btn btn-link p-0 m-0 align-baseline">
          <i class="bi bi-trash "></i>
        </button>
    </form>
    <form class="form-display"
        hx-get="{% url 'projects:projects_update' project.id %}" 
        hx-target="#project-update-{{project.id}}"
        hx-swap="outerHTML">
      {% csrf_token %}
      <button type="submit" class="btn btn-link p-0 m-0 align-baseline">
      <i class="bi bi-pencil"></i>
      </button>
    </form>
  </div>  
</div>

templates/todo_list/task_form.html
<form class="card p-2 bg-secondary p-2 text-dark rounded-0" id="task-form-{{project.id}}"
    hx-post="{% url 'projects:task_create' project.id %}"
    hx-target="#task-form-{{project.id}}"
    hx-swap="outerHTML">
    {%csrf_token%}
    <div class="input-group">
        <button
            hx-get="{% url 'projects:task_create' project.id %}"
            type="button" class="btn btn-success rounded-circle me-2">
            <i class="bi bi-plus-circle-fill"></i>
        </button>
        <input 
            type="text" 
            class="form-control " 
            placeholder="Start typing to create new task" 
            autocomplete="off"
            hx-get="{% url 'projects:task_create' project.id %}"
            hx-trigger="keyup">
    </div>
</form>

templates/todo_list/task_list.html
{% load static %}
<div id="test-{{project.id}}">
    {% include 'todo_list/task_form.html' with project=project %}
    <div class="p-3 bg-body rounded-top custom-rounded shadow-sm" id="task-body-{{project.id}}">
        {% if form.errors %}
        <div class="alert alert-primary d-flex align-items-center" role="alert">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
                <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
            </svg>
            <div>
                {{form.priority.errors.0}}
            </div>
        </div>
        {% endif %}
        {% for task in project.tasks.all %}
        <div id="task-{{ task.id }}" class="d-flex justify-content-between align-items-center p-3 text-muted pt-3 border-bottom" id="task-{{task.id}}">
        <div class="form-check  me-3">
            <form >
                {% csrf_token %}
                <input class="form-check-input" type="checkbox" value="completed" name="completed" id="{{task.id}}" {% if task.completed %} checked {% endif %}
                hx-post="{% url 'projects:task_completed' task.id %}">
            </form>
            
            <label class="form-check-label d-flex" for="{{task.id}}">
                {{task.content}}
            </label>
        </div>
        <div class="d-flex align-items-center">
            <div class="d-grid  gap-0 me-5">
                <p class="me-4 d-flex justify-content-between align-items-center ">{{task.deadline}}</p>
            </div>
            <div class="d-grid  gap-0 me-2">
                <form class="form-display"
                    hx-post="{% url 'projects:task_priority' task.id %}"
                    hx-target="#test-{{project.id}}"
                    hx-swap="outerHTML">
                    <input type="number" name="priority" value="1" hidden>
                    {% csrf_token %}
                    <button type="submit" class="btn btn-link p-0 m-0 align-baseline ">
                        <i class="bi bi-arrow-bar-up fc-5"></i>
                    </button>
                </form>
                <form class="form-display"
                    hx-post="{% url 'projects:task_priority' task.id %}"
                    hx-target="#test-{{project.id}}"
                    hx-swap="outerHTML">
                    <input type="number" name="priority" value="-1" hidden>
                    {% csrf_token %}
                    <button type="submit" class="btn btn-link p-0 m-0 align-baseline ">
                        <i class="bi bi-arrow-bar-down fc-5"></i>
                    </button>
                </form>
            </div>
            <form class="form-display"
                hx-post="{% url 'projects:task_delete' task.id %}"
                hx-target="#task-{{task.id}}"
                hx-swap="delete">
                {% csrf_token %}
                <button type="submit" class="btn btn-link p-0 m-0 align-baseline me-2">
                    <i class="bi bi-trash"></i>
                </button>
            </form>
            <form class="form-display"
                hx-get="{% url 'projects:task_update' task.id %}"
                hx-target="#task-{{task.id}}"
                hx-swap="outerHTML">
                {% csrf_token %}
                <button type="submit" class="btn btn-link p-0 m-0 align-baseline">
                    <i class="bi bi-pencil"></i>
                </button>
            </form>
        </div>
        </div>
        {% endfor %}
    </div>
</div>